### ISSUE TITLE
Error response 200 when logging in, not getting RSS updates

### ISSUE THREAD

**Issue by ksbrar** [gumcast/gumcast-client#11]
![Screenshot from 2021-12-16 21-59-23](https://user-images.githubusercontent.com/4261338/146481874-3a9165ff-cb33-4aff-a042-287002aaec3c.png)

**Comment by bcomnes** [comment]
Yeah, looks like we are getting rate limited. Just curious, if you are currently getting 429s, are you able to log in and generate a new token/feed that isn't getting 429ed?

I was able to log in on a few accounts just now. 

Worst case scenario, just wait a bit and it will start working again.  If it doesn't try logging out and logging in, and making a new feed.  I had to adjust how tokens were acquired a little bit ago, so maybe you have an older token.

**Comment by ksbrar** [comment]
Looks like it's resolved for me now. But where is the option to generate a new token anyway? I don't see it in the default view.

**Comment by bcomnes** [comment]
Logging out and logging back in generates a new token each time.

**Comment by ksbrar** [comment]
Gotcha, not sure how to test it now that it's working though :P

**Comment by bcomnes** [comment]
You would subscribe to a feed generated after logging in again basically, and unsubscribe from the old feed.

**Comment by ksbrar** [comment]
Ok I see, do you still want me to do this? (My previous feeds/tokens are now working.)

**Comment by bcomnes** [comment]
Nah, you don't have to, unless you want to try something if it happens again.

**Comment by bcomnes** [comment]
I'm going to close this out for now.

**Comment by ksbrar** [comment]
Happening for me again, logging out/in doesn't seem to help - library view still shows 200 code.

**Comment by bcomnes** [comment]
<img width="631" alt="Screen Shot 2021-12-21 at 8 43 46 AM" src="https://user-images.githubusercontent.com/166301/146966909-3c46ae10-be89-44fc-a971-03d488b4eb51.png">

Was only happening like once a day, which is usually fine since your podcast app will download episodes while they are available, but something started hammering the system the other night. I'll look into it when I get some time, apologies for the the disruption.

**Comment by bcomnes** [comment]
Oh actually these are 404s, not 429s so something else might be going on.

**Comment by bcomnes** [comment]
Ok, looks like the API URL changed and it also went back to the old way of fetching files. Should be fixed now.

**Comment by ksbrar** [comment]
Working for me, thanks again!

**Comment by bcomnes** [comment]
<img width="620" alt="Screen Shot 2021-12-24 at 2 38 29 PM" src="https://user-images.githubusercontent.com/166301/147373613-3079a15c-788a-4bc5-b441-7d6bd483db1d.png">

After going back to a single request to lookup feeds, we are back to days with 0 throttling.
