### ISSUE TITLE
Error: Response status !== 200

### ISSUE THREAD

**Issue by jackmaninov** [gumcast/gumcast-client#38]
Hello,

Yesterday I was connected fine and downloading podcast episodes, however today the same episodes could not download. I've confirmed my gumroad account is fine. 

I've tried resetting my token here, but after logging in I only get:

Error: Response status !== 200

Problem with gumroad API today?

**Comment by jackmaninov** [comment]
Nevermind, seems to have resolved itself

**Comment by bcomnes** [comment]
The service has been experience rate limiting more lately. Something changed upstream.
