### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by protobronze** [gumcast/gumcast-client#39]
Right on the web page after logging in:

Error: Response status !== 200

**Comment by bcomnes** [comment]
The API has been rate limiting lately. I need to set up a re-deploy to periodically acquire a new outgoing IP address. Unfortunately the solution right now is to retry after a bit, it will work.

**Comment by bcomnes** [comment]
I added a cron job to redeploy regions every hour. I think this should help simulate the former heroku hosting environment closer and help reduce the chance of the service getting rate limited.

**Comment by bcomnes** [comment]
Feel free to re-open if it keeps happening or you see other issues.
